"""
Docs Sync Task (Self-Generation) - MVP

Purpose: Keep the Selenium Learning Wiki in sync with the test code.
This script walks the tests directory, extracts metadata from test files,
and generates corresponding markdown pages for the wiki.

MVP Approach (v0.1):
- Uses os.walk and regular expressions for simplicity and speed.
- Extracts top-level docstrings from test files.
- Extracts pytest markers.
- Generates a markdown file for each test.
- Generates a main Traceability Matrix page.
"""
import os
import re
import argparse
from pathlib import Path

# --- Configuration ---
DOCSTRING_HEADER_PATTERN = re.compile(r'\"\"\"(.*?)\"\"\"', re.DOTALL)
MARKER_PATTERN = re.compile(r'@pytest\.mark\.(\w+)')
LESSON_TEMPLATE = """
# Lesson: {lesson_title}

{lesson_docstring}

---

## Test Implementation

```python
{test_code}
```

---

## Traceability

- **Test File**: `{test_path}`
- **Markers**: `{markers}`
"""

TRACEABILITY_MATRIX_TEMPLATE = """
# Traceability Matrix

This matrix maps our test cases to the features they cover and the concepts they teach.
It is automatically generated by `tools/sync_docs.py`.

| Test File | Purpose | Markers |
|-----------|---------|---------|
{table_rows}
"""

def parse_test_file(file_path):
    """
    Parses a single test file to extract its docstring, markers, and code.
    """
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()

        docstring_match = DOCSTRING_HEADER_PATTERN.search(content)
        docstring = docstring_match.group(1).strip() if docstring_match else "No description provided."
        
        markers = MARKER_PATTERN.findall(content)
        
        # Extract purpose for traceability matrix
        purpose_match = re.search(r'Purpose:\s*(.*)', docstring)
        purpose = purpose_match.group(1).strip() if purpose_match else "N/A"

        return {
            "docstring": docstring,
            "markers": sorted(list(set(markers))),
            "code": content,
            "purpose": purpose
        }
    except Exception as e:
        print(f"Error parsing file {file_path}: {e}")
        return None

def generate_docs(src_dir, out_dir):
    """
    Walks the source directory, parses test files, and generates markdown docs.
    """
    src_path = Path(src_dir)
    out_path = Path(out_dir)
    
    out_path.mkdir(parents=True, exist_ok=True)
    
    all_tests_metadata = []

    for root, _, files in os.walk(src_path):
        for file in files:
            if file.startswith("test_") and file.endswith(".py"):
                file_path = Path(root) / file
                metadata = parse_test_file(file_path)
                
                if metadata:
                    # Generate individual lesson page
                    lesson_title = file.replace('.py', '').replace('_', ' ').title()
                    markers_str = ", ".join([f"`@{m}`" for m in metadata['markers']])
                    
                    lesson_content = LESSON_TEMPLATE.format(
                        lesson_title=lesson_title,
                        lesson_docstring=metadata['docstring'],
                        test_code=metadata['code'],
                        test_path=file_path.relative_to(src_path.parent),
                        markers=markers_str
                    )
                    
                    lesson_filename = f"{file.replace('.py', '.md')}"
                    with open(out_path / lesson_filename, 'w', encoding='utf-8') as f:
                        f.write(lesson_content)
                    
                    print(f"Generated doc: {lesson_filename}")
                    
                    # Store metadata for the matrix
                    all_tests_metadata.append({
                        "path": file_path.relative_to(src_path.parent),
                        "purpose": metadata['purpose'],
                        "markers": markers_str
                    })

    # Generate Traceability Matrix
    table_rows = ""
    for meta in sorted(all_tests_metadata, key=lambda x: x['path']):
        table_rows += f"| `{meta['path']}` | {meta['purpose']} | {meta['markers']} |\n"
        
    matrix_content = TRACEABILITY_MATRIX_TEMPLATE.format(table_rows=table_rows)
    matrix_filename = "Traceability_Matrix.md"
    with open(out_path / matrix_filename, 'w', encoding='utf-8') as f:
        f.write(matrix_content)
    print(f"Generated doc: {matrix_filename}")


def main():
    parser = argparse.ArgumentParser(description="Generate documentation from pytest tests.")
    parser.add_argument('--src', default='tests', help="Source directory containing test files.")
    parser.add_argument('--out', default='docs/wiki', help="Output directory for generated markdown files.")
    args = parser.parse_args()
    
    print(f"Starting documentation sync...\nSource: {args.src}\nOutput: {args.out}")
    generate_docs(args.src, args.out)
    print("\nDocumentation sync complete.")

if __name__ == "__main__":
    main()
